ro:
  msg:
    learning:
      shop:
        routematrix:
          key: TrBIVkFCj32FLA7CX0Dyyfls0sbD6mab
          url: http://www.mapquestapi.com/directions/v2/routematrix?key=

spring:
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/postgres
    username: ${POSTGRES_USER:postgres}
  flyway:
    clean-on-validation-error: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URL}

# Strategy Pattern -> possible values are 'single location', 'most abundant' and 'proximity'
strategy: proximity
